polaris.persistence.type=relational-jdbc
polaris.persistence.relational.jdbc.database-type=postgresql
polaris.persistence.relational.jdbc.max-retries=5
polaris.persistence.relational.jdbc.initial-delay-in-ms=100
polaris.persistence.relational.jdbc.max-duration-in-ms=5000

polaris.realm-context.type=default
polaris.realm-context.realms=POLARIS
polaris.realm-context.header-name=Polaris-Realm
polaris.realm-context.require-header=false

polaris.features."ALLOW_INSECURE_STORAGE_TYPES"=true
polaris.features."SUPPORTED_CATALOG_STORAGE_TYPES"=["S3"]
polaris.readiness.ignore-severe-issues=true
polaris.authentication.type=internal

quarkus.otel.sdk.disabled=true
quarkus.log.file.enabled=false
quarkus.http.access-log.enabled=true
