CREATE TABLE IF NOT EXISTS serving_cdc.customers_events
(
    sync_run_seq UInt64,
    sync_run_id String,
    event_id String,
    op LowCardinality(String),
    is_snapshot Bool,
    is_deleted Bool,
    apply_status LowCardinality(String),
    error_code Nullable(String),
    error_message Nullable(String),
    customer_id Nullable(String),
    customer_unique_id Nullable(String),
    customer_zip_code_prefix Nullable(String),
    customer_city Nullable(String),
    customer_state Nullable(FixedString(2)),
    source_ts DateTime64(6, 'UTC'),
    source_server_id Nullable(UInt64),
    source_gtid Nullable(String),
    source_binlog_file Nullable(String),
    source_binlog_file_index Nullable(Int64),
    source_binlog_pos Nullable(Int64),
    source_row Nullable(Int32),
    transaction_id Nullable(String),
    transaction_total_order Nullable(UInt64),
    transaction_data_collection_order Nullable(UInt64),
    kafka_topic String,
    kafka_partition Int32,
    kafka_offset Int64,
    kafka_timestamp DateTime64(6, 'UTC'),
    key_schema_id Nullable(Int32),
    value_schema_id Nullable(Int32),
    schema_fingerprint Nullable(String),
    contract_version UInt32,
    before_row_hash Nullable(String),
    after_row_hash Nullable(String),
    row_hash Nullable(String),
    bronze_ingested_at DateTime64(6, 'UTC'),
    normalized_at DateTime64(6, 'UTC')
)
ENGINE = MergeTree
PARTITION BY sync_run_seq
ORDER BY (kafka_partition, kafka_offset);

CREATE TABLE IF NOT EXISTS serving_cdc.orders_events
(
    sync_run_seq UInt64,
    sync_run_id String,
    event_id String,
    op LowCardinality(String),
    is_snapshot Bool,
    is_deleted Bool,
    apply_status LowCardinality(String),
    error_code Nullable(String),
    error_message Nullable(String),
    order_id Nullable(String),
    customer_id Nullable(String),
    order_status LowCardinality(Nullable(String)),
    order_purchase_timestamp Nullable(DateTime64(6, 'UTC')),
    order_approved_at Nullable(DateTime64(6, 'UTC')),
    order_delivered_carrier_date Nullable(DateTime64(6, 'UTC')),
    order_delivered_customer_date Nullable(DateTime64(6, 'UTC')),
    order_estimated_delivery_date Nullable(DateTime64(6, 'UTC')),
    source_ts DateTime64(6, 'UTC'),
    source_server_id Nullable(UInt64),
    source_gtid Nullable(String),
    source_binlog_file Nullable(String),
    source_binlog_file_index Nullable(Int64),
    source_binlog_pos Nullable(Int64),
    source_row Nullable(Int32),
    transaction_id Nullable(String),
    transaction_total_order Nullable(UInt64),
    transaction_data_collection_order Nullable(UInt64),
    kafka_topic String,
    kafka_partition Int32,
    kafka_offset Int64,
    kafka_timestamp DateTime64(6, 'UTC'),
    key_schema_id Nullable(Int32),
    value_schema_id Nullable(Int32),
    schema_fingerprint Nullable(String),
    contract_version UInt32,
    before_row_hash Nullable(String),
    after_row_hash Nullable(String),
    row_hash Nullable(String),
    bronze_ingested_at DateTime64(6, 'UTC'),
    normalized_at DateTime64(6, 'UTC')
)
ENGINE = MergeTree
PARTITION BY sync_run_seq
ORDER BY (kafka_partition, kafka_offset);

CREATE TABLE IF NOT EXISTS serving_cdc.order_items_events
(
    sync_run_seq UInt64,
    sync_run_id String,
    event_id String,
    op LowCardinality(String),
    is_snapshot Bool,
    is_deleted Bool,
    apply_status LowCardinality(String),
    error_code Nullable(String),
    error_message Nullable(String),
    order_id Nullable(String),
    order_item_id Nullable(Int32),
    product_id Nullable(String),
    seller_id Nullable(String),
    shipping_limit_date Nullable(DateTime64(6, 'UTC')),
    price Nullable(Decimal(18, 2)),
    freight_value Nullable(Decimal(18, 2)),
    source_ts DateTime64(6, 'UTC'),
    source_server_id Nullable(UInt64),
    source_gtid Nullable(String),
    source_binlog_file Nullable(String),
    source_binlog_file_index Nullable(Int64),
    source_binlog_pos Nullable(Int64),
    source_row Nullable(Int32),
    transaction_id Nullable(String),
    transaction_total_order Nullable(UInt64),
    transaction_data_collection_order Nullable(UInt64),
    kafka_topic String,
    kafka_partition Int32,
    kafka_offset Int64,
    kafka_timestamp DateTime64(6, 'UTC'),
    key_schema_id Nullable(Int32),
    value_schema_id Nullable(Int32),
    schema_fingerprint Nullable(String),
    contract_version UInt32,
    before_row_hash Nullable(String),
    after_row_hash Nullable(String),
    row_hash Nullable(String),
    bronze_ingested_at DateTime64(6, 'UTC'),
    normalized_at DateTime64(6, 'UTC')
)
ENGINE = MergeTree
PARTITION BY sync_run_seq
ORDER BY (kafka_partition, kafka_offset);

CREATE TABLE IF NOT EXISTS serving_cdc.order_payments_events
(
    sync_run_seq UInt64,
    sync_run_id String,
    event_id String,
    op LowCardinality(String),
    is_snapshot Bool,
    is_deleted Bool,
    apply_status LowCardinality(String),
    error_code Nullable(String),
    error_message Nullable(String),
    order_id Nullable(String),
    payment_sequential Nullable(Int32),
    payment_type LowCardinality(Nullable(String)),
    payment_installments Nullable(Int32),
    payment_value Nullable(Decimal(18, 2)),
    source_ts DateTime64(6, 'UTC'),
    source_server_id Nullable(UInt64),
    source_gtid Nullable(String),
    source_binlog_file Nullable(String),
    source_binlog_file_index Nullable(Int64),
    source_binlog_pos Nullable(Int64),
    source_row Nullable(Int32),
    transaction_id Nullable(String),
    transaction_total_order Nullable(UInt64),
    transaction_data_collection_order Nullable(UInt64),
    kafka_topic String,
    kafka_partition Int32,
    kafka_offset Int64,
    kafka_timestamp DateTime64(6, 'UTC'),
    key_schema_id Nullable(Int32),
    value_schema_id Nullable(Int32),
    schema_fingerprint Nullable(String),
    contract_version UInt32,
    before_row_hash Nullable(String),
    after_row_hash Nullable(String),
    row_hash Nullable(String),
    bronze_ingested_at DateTime64(6, 'UTC'),
    normalized_at DateTime64(6, 'UTC')
)
ENGINE = MergeTree
PARTITION BY sync_run_seq
ORDER BY (kafka_partition, kafka_offset);

CREATE TABLE IF NOT EXISTS serving_cdc.order_reviews_events
(
    sync_run_seq UInt64,
    sync_run_id String,
    event_id String,
    op LowCardinality(String),
    is_snapshot Bool,
    is_deleted Bool,
    apply_status LowCardinality(String),
    error_code Nullable(String),
    error_message Nullable(String),
    review_id Nullable(String),
    order_id Nullable(String),
    review_score Nullable(Int32),
    review_comment_title Nullable(String),
    review_comment_message Nullable(String),
    review_creation_date Nullable(DateTime64(6, 'UTC')),
    review_answer_timestamp Nullable(DateTime64(6, 'UTC')),
    source_ts DateTime64(6, 'UTC'),
    source_server_id Nullable(UInt64),
    source_gtid Nullable(String),
    source_binlog_file Nullable(String),
    source_binlog_file_index Nullable(Int64),
    source_binlog_pos Nullable(Int64),
    source_row Nullable(Int32),
    transaction_id Nullable(String),
    transaction_total_order Nullable(UInt64),
    transaction_data_collection_order Nullable(UInt64),
    kafka_topic String,
    kafka_partition Int32,
    kafka_offset Int64,
    kafka_timestamp DateTime64(6, 'UTC'),
    key_schema_id Nullable(Int32),
    value_schema_id Nullable(Int32),
    schema_fingerprint Nullable(String),
    contract_version UInt32,
    before_row_hash Nullable(String),
    after_row_hash Nullable(String),
    row_hash Nullable(String),
    bronze_ingested_at DateTime64(6, 'UTC'),
    normalized_at DateTime64(6, 'UTC')
)
ENGINE = MergeTree
PARTITION BY sync_run_seq
ORDER BY (kafka_partition, kafka_offset);

CREATE TABLE IF NOT EXISTS serving_cdc.products_events
(
    sync_run_seq UInt64,
    sync_run_id String,
    event_id String,
    op LowCardinality(String),
    is_snapshot Bool,
    is_deleted Bool,
    apply_status LowCardinality(String),
    error_code Nullable(String),
    error_message Nullable(String),
    product_id Nullable(String),
    product_category_name Nullable(String),
    product_name_lenght Nullable(Int32),
    product_description_lenght Nullable(Int32),
    product_photos_qty Nullable(Int32),
    product_weight_g Nullable(Int32),
    product_length_cm Nullable(Int32),
    product_height_cm Nullable(Int32),
    product_width_cm Nullable(Int32),
    source_ts DateTime64(6, 'UTC'),
    source_server_id Nullable(UInt64),
    source_gtid Nullable(String),
    source_binlog_file Nullable(String),
    source_binlog_file_index Nullable(Int64),
    source_binlog_pos Nullable(Int64),
    source_row Nullable(Int32),
    transaction_id Nullable(String),
    transaction_total_order Nullable(UInt64),
    transaction_data_collection_order Nullable(UInt64),
    kafka_topic String,
    kafka_partition Int32,
    kafka_offset Int64,
    kafka_timestamp DateTime64(6, 'UTC'),
    key_schema_id Nullable(Int32),
    value_schema_id Nullable(Int32),
    schema_fingerprint Nullable(String),
    contract_version UInt32,
    before_row_hash Nullable(String),
    after_row_hash Nullable(String),
    row_hash Nullable(String),
    bronze_ingested_at DateTime64(6, 'UTC'),
    normalized_at DateTime64(6, 'UTC')
)
ENGINE = MergeTree
PARTITION BY sync_run_seq
ORDER BY (kafka_partition, kafka_offset);

CREATE TABLE IF NOT EXISTS serving_cdc.sellers_events
(
    sync_run_seq UInt64,
    sync_run_id String,
    event_id String,
    op LowCardinality(String),
    is_snapshot Bool,
    is_deleted Bool,
    apply_status LowCardinality(String),
    error_code Nullable(String),
    error_message Nullable(String),
    seller_id Nullable(String),
    seller_zip_code_prefix Nullable(String),
    seller_city Nullable(String),
    seller_state Nullable(FixedString(2)),
    source_ts DateTime64(6, 'UTC'),
    source_server_id Nullable(UInt64),
    source_gtid Nullable(String),
    source_binlog_file Nullable(String),
    source_binlog_file_index Nullable(Int64),
    source_binlog_pos Nullable(Int64),
    source_row Nullable(Int32),
    transaction_id Nullable(String),
    transaction_total_order Nullable(UInt64),
    transaction_data_collection_order Nullable(UInt64),
    kafka_topic String,
    kafka_partition Int32,
    kafka_offset Int64,
    kafka_timestamp DateTime64(6, 'UTC'),
    key_schema_id Nullable(Int32),
    value_schema_id Nullable(Int32),
    schema_fingerprint Nullable(String),
    contract_version UInt32,
    before_row_hash Nullable(String),
    after_row_hash Nullable(String),
    row_hash Nullable(String),
    bronze_ingested_at DateTime64(6, 'UTC'),
    normalized_at DateTime64(6, 'UTC')
)
ENGINE = MergeTree
PARTITION BY sync_run_seq
ORDER BY (kafka_partition, kafka_offset);

CREATE TABLE IF NOT EXISTS serving_cdc.product_category_translation_events
(
    sync_run_seq UInt64,
    sync_run_id String,
    event_id String,
    op LowCardinality(String),
    is_snapshot Bool,
    is_deleted Bool,
    apply_status LowCardinality(String),
    error_code Nullable(String),
    error_message Nullable(String),
    product_category_name Nullable(String),
    product_category_name_english Nullable(String),
    source_ts DateTime64(6, 'UTC'),
    source_server_id Nullable(UInt64),
    source_gtid Nullable(String),
    source_binlog_file Nullable(String),
    source_binlog_file_index Nullable(Int64),
    source_binlog_pos Nullable(Int64),
    source_row Nullable(Int32),
    transaction_id Nullable(String),
    transaction_total_order Nullable(UInt64),
    transaction_data_collection_order Nullable(UInt64),
    kafka_topic String,
    kafka_partition Int32,
    kafka_offset Int64,
    kafka_timestamp DateTime64(6, 'UTC'),
    key_schema_id Nullable(Int32),
    value_schema_id Nullable(Int32),
    schema_fingerprint Nullable(String),
    contract_version UInt32,
    before_row_hash Nullable(String),
    after_row_hash Nullable(String),
    row_hash Nullable(String),
    bronze_ingested_at DateTime64(6, 'UTC'),
    normalized_at DateTime64(6, 'UTC')
)
ENGINE = MergeTree
PARTITION BY sync_run_seq
ORDER BY (kafka_partition, kafka_offset);
